/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menu;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Gastos extends javax.swing.JInternalFrame {

    
    public Gastos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        coca = new javax.swing.JTextField();
        pilsen = new javax.swing.JTextField();
        inca = new javax.swing.JTextField();
        four = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        limpieza = new javax.swing.JTextField();
        seguridad = new javax.swing.JTextField();
        salarios = new javax.swing.JTextField();
        otro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tex = new javax.swing.JTextArea();
        totalg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GASTOS MENSUALES DEL HOTEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 90));

        jLabel2.setText("COCA COLA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setText("PILSEN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setText("INCA KOLA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setText("FOUR LOCO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        getContentPane().add(coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));
        getContentPane().add(pilsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, -1));
        getContentPane().add(inca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, -1));
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        jLabel6.setText("LIMPIEZA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel7.setText("SEGURIDAD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel8.setText("SALARIOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));
        getContentPane().add(limpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, -1));
        getContentPane().add(seguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 120, -1));
        getContentPane().add(salarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 120, -1));
        getContentPane().add(otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 120, -1));

        jLabel9.setText("OTROS GASTOS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        tex.setColumns(20);
        tex.setRows(5);
        jScrollPane1.setViewportView(tex);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 700, 250));
        getContentPane().add(totalg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 150, 30));

        jLabel10.setText("TOTAL DE GASTOS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, 30));

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double a,ca,b,cb,c,cc,d,cd,e,f,g,h,total;
        a=Double.parseDouble(coca.getText());
        ca=a*3.20;
        b=Double.parseDouble(pilsen.getText());
        cb=b*5;
        c=Double.parseDouble(inca.getText());
        cc=c*3.20;
        d=Double.parseDouble(four.getText());
        cd=d*4;
        e=Double.parseDouble(four.getText());
        f=Double.parseDouble(four.getText());
        g=Double.parseDouble(four.getText());
        h=Double.parseDouble(four.getText());
        total=ca+cb+cc+cd+e+f+g+h;
        tex.append("GASTOS MENSUALES:\n\n");
        tex.append("COCA COLA: "+ca+"\n\n");
        tex.append("PILSEN: "+cb+"\n\n");
        tex.append("INCA KOLA: "+cc+"\n\n");
        tex.append("FOUR LOCO: "+cd+"\n\n");
        tex.append("LIMPIEZA: "+limpieza.getText()+"\n\n");
        tex.append("SEGURIDAD: "+seguridad.getText()+"\n\n");
        tex.append("SALARIOS: "+salarios.getText()+"\n\n");
        tex.append("OTROS GASTOS: "+otro.getText()+"\n\n");
        totalg.setText(""+total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coca;
    private javax.swing.JTextField four;
    private javax.swing.JTextField inca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField limpieza;
    private javax.swing.JTextField otro;
    private javax.swing.JTextField pilsen;
    private javax.swing.JTextField salarios;
    private javax.swing.JTextField seguridad;
    private javax.swing.JTextArea tex;
    private javax.swing.JTextField totalg;
    // End of variables declaration//GEN-END:variables
}
