/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menu;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MenuGerente extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Gerente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 170, 60));

        jButton1.setText("Clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 70));

        jButton2.setText("Gastos");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 180, 100));

        jButton3.setText("Reporte de Empleados");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 200, 110));

        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 120, 100));

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        // Puedes adaptar esto según cómo estés almacenando tus datos
        String datosHabitacion101 = leerDatosHabitacion("Habitacion101Clientes.txt");
        String datosHabitacion102 = leerDatosHabitacion("Habitacion102Clientes.txt");
        String datosHabitacion103 = leerDatosHabitacion("Habitacion103Clientes.txt");
        String datosHabitacion104 = leerDatosHabitacion("Habitacion104Clientes.txt");
        String datosHabitacion105 = leerDatosHabitacion("Habitacion105Clientes.txt");
        String datosHabitacion106 = leerDatosHabitacion("Habitacion106Clientes.txt");
        // Repite para otras habitaciones

        // Agrega los datos al JTextArea
        Text.append("Habitación 101:\n" + datosHabitacion101 + "\n\n");
        Text.append("Habitación 102:\n" + datosHabitacion102 + "\n\n");
        Text.append("Habitación 103:\n" + datosHabitacion103 + "\n\n");
        Text.append("Habitación 104:\n" + datosHabitacion104 + "\n\n");
        Text.append("Habitación 105:\n" + datosHabitacion105 + "\n\n");
        Text.append("Habitación 106:\n" + datosHabitacion106 + "\n\n");
        // Repite para otras habitaciones...
        Text.setText("");

        // Crea un cuadro de diálogo para mostrar los datos
        JOptionPane.showMessageDialog(this, Text, "Datos de Habitaciones", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Text.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed
    private String leerDatosHabitacion(String DatosGeneralesdeClientes) {
        StringBuilder datos = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader(DatosGeneralesdeClientes))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                datos.append(linea).append("\n");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return datos.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
